// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_ZMRtcEs3XnXCkenezjF1TAjYpen4mw',
    appId: '1:375511123849:web:2d972d44995cbef2618358',
    messagingSenderId: '375511123849',
    projectId: 'learnlogin-302a6',
    authDomain: 'learnlogin-302a6.firebaseapp.com',
    storageBucket: 'learnlogin-302a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW1eyuOC1TIfo2zoCoL4LxcOKSpku9oTU',
    appId: '1:375511123849:android:bc9308858d4e7079618358',
    messagingSenderId: '375511123849',
    projectId: 'learnlogin-302a6',
    storageBucket: 'learnlogin-302a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5E1zk6zQaejD7_nsrfI3JMdXBIfRzuIA',
    appId: '1:375511123849:ios:b80adcbf3ca8a6a7618358',
    messagingSenderId: '375511123849',
    projectId: 'learnlogin-302a6',
    storageBucket: 'learnlogin-302a6.appspot.com',
    iosClientId: '375511123849-5gbaq74471hsja9rl8fhbkpp9017jm8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5E1zk6zQaejD7_nsrfI3JMdXBIfRzuIA',
    appId: '1:375511123849:ios:b80adcbf3ca8a6a7618358',
    messagingSenderId: '375511123849',
    projectId: 'learnlogin-302a6',
    storageBucket: 'learnlogin-302a6.appspot.com',
    iosClientId: '375511123849-5gbaq74471hsja9rl8fhbkpp9017jm8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.learn',
  );
}
